services:
  ros-master:
    build: .
    container_name: ros_turtlebot3_container
    ports:
      - "9090:9090"
      - "8080:8080"
    environment:
      - TURTLEBOT3_MODEL=waffle
    privileged: true
    restart: unless-stopped
